export const ALL_SCHOOLS_REQUEST = "ALL_SCHOOLS_REQUEST";
export const ALL_SCHOOLS_SUCCESS = "ALL_SCHOOLS_SUCCESS";
export const ALL_SCHOOLS_FAIL = "ALL_SCHOOLS_FAIL";

export const ADD_SCHOOL_REQUEST = "ADD_SCHOOL_REQUEST";
export const ADD_SCHOOL_SUCCESS = "ADD_SCHOOL_SUCCESS";
export const ADD_SCHOOL_FAIL = "ADD_SCHOOL_FAIL";
export const ADD_SCHOOL_RESET = "ADD_SCHOOL_RESET";

export const SCHOOL_DETAIL_REQUEST = "SCHOOL_DETAIL_REQUEST";
export const SCHOOL_DETAIL_SUCCESS = "SCHOOL_DETAIL_SUCCESS";
export const SCHOOL_DETAIL_FAIL = "SCHOOL_DETAIL_FAIL";

export const STUDENT_JOIN_REQUEST = "STUDENT_JOIN_REQUEST";
export const STUDENT_JOIN_SUCCESS = "STUDENT_JOIN_SUCCESS";
export const STUDENT_JOIN_FAIL = "STUDENT_JOIN_FAIL";

export const ALL_SCHOOL_DEMAND_REQUEST = "ALL_SCHOOL_DEMAND_REQUEST";
export const ALL_SCHOOL_DEMAND_SUCCESS = "ALL_SCHOOL_DEMAND_SUCCESS";
export const ALL_SCHOOL_DEMAND_FAIL = "ALL_SCHOOL_DEMAND_FAIL";

export const DELETE_SCHOOL_REQUEST = "DELETE_SCHOOL_REQUEST";
export const DELETE_SCHOOL_SUCCESS = "DELETE_SCHOOL_SUCCESS";
export const DELETE_SCHOOL_RESET = "DELETE_SCHOOL_RESET";
export const DELETE_SCHOOL_FAIL = "DELETE_SCHOOL_FAIL";

export const DELETE_DEMAND_SCHOOL_REQUEST = "DELETE_DEMAND_SCHOOL_REQUEST";
export const DELETE_DEMAND_SCHOOL_SUCCESS = "DELETE_DEMAND_SCHOOL_SUCCESS";
export const DELETE_DEMAND_SCHOOL_RESET = "DELETE_DEMAND_SCHOOL_RESET";
export const DELETE_DEMAND_SCHOOL_FAIL = "DELETE_DEMAND_SCHOOL_FAIL";

export const NEW_SCHOOL_REQUEST = "NEW_SCHOOL_REQUEST";
export const NEW_SCHOOL_SUCCESS = "NEW_SCHOOL_SUCCESS";
export const NEW_SCHOOL_RESET = "NEW_SCHOOL_RESET";
export const NEW_SCHOOL_FAIL = "NEW_SCHOOL_FAIL";

export const UPDATE_SCHOOL_REQUEST = "UPDATE_SCHOOL_REQUEST";
export const UPDATE_SCHOOL_SUCCESS = "UPDATE_SCHOOL_SUCCESS";
export const UPDATE_SCHOOL_RESET = "UPDATE_SCHOOL_RESET";
export const UPDATE_SCHOOL_FAIL = "UPDATE_SCHOOL_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
